### PR TITLE
Update composer-playground.yaml for new ID card metadata format

### PR DESCRIPTION
**Pull request by bestbeforetoday**
Changes required for compatibility with Composer 0.13.0.

Signed-off-by: Mark S. Lewis <Mark_Lewis@uk.ibm.com>

### CODE REVIEW

**Comment by jt-nti** [comment]
Waiting for bluemix to finish creating a cluster so I can test this

**Comment by jt-nti** [comment]
Hmm, it was looking good. I've deployed a test network without problems -> http://184.172.233.78:31080/ but just investigating an error connecting to the new network...

**Comment by jt-nti** [comment]
Sounds like that error is a known issue so this fix is good to go if someone can merge

**Comment by dhyey20** [comment]
thanks @bestbeforetoday @jt-nti

**Pull request merged**
