### PR TITLE
Update to fix composer-import-card.yaml (#108)

### PR DESCRIPTION
**Pull request by rischioto**
composer-import-card.yaml, fixed, 
the Certification Authorities session was wrong.

### CODE REVIEW

**Comment by johnwalicki** [comment]
Lots of users are tripping on the create_all.sh bug that this branch fixes.  Can we get this patch merged ASAP?

**Comment by rischioto** [comment]
Guys, unfortunately I discovery that this fix just the first part of the issue with composer_import_card, it makes the scripts finishes, but compose are sill not working, looks that there is more issues on the yaml. see issue #110

**Comment by timroster** [comment]
I've created #114 which includes changes proposed in this PR and other fixes to the format of the endpoints in `composer-card-import.yaml`

**Comment by dhyey20** [comment]
fixed in https://github.com/IBM-Blockchain/ibm-container-service/pull/114. thanks @rischioto closing this one.

**Pull request closed without merging**
