### PR TITLE
Moving to 1.1 fabric 

### PR DESCRIPTION
**Pull request by dhyey20**
Thanks @lvndry for https://github.com/IBM-Blockchain/ibm-container-service/pull/102. I have made some more changes to use the latest `couchdb` image. And updated a couple of environment variables, along with updating the `configtx.yaml` to v1.1 level.

### CODE REVIEW

**Comment by lvndry** [comment]
So I can close my PR ?

**Comment by mrshah-at-ibm** [comment]
yes, we will merge this - it gives you credits for your contributions 😄

**Comment by lvndry** [comment]
Alright great! :smile: Also I was asked to add the env variable CORE_PEER_GOSSIP_USELEADERELECTION=true and CORE_PEER_GOSSIP_ORGLEADER=false to the peers please add it before merging

**Comment by lvndry** [comment]
Why am I not mentioned as a contributor?

Le mar. 3 juil. 2018 à 15:34, Mihir Shah <notifications@github.com> a
écrit :

**Comment by mrshah-at-ibm** [comment]
@lvndry I didn't know that "Squash and merge" would do this. It did show you as author on this PR.

image


I apologize. If you want I can revert the commit and we can redo the PR.

**Pull request merged**
